# Generated by Django 5.0 on 2024-03-04 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraccount_activation_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='activation_token',
        ),
    ]
