# Generated by Django 5.0 on 2024-03-04 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(default='Study', on_delete=django.db.models.deletion.CASCADE, to='tasks.category'),
        ),
    ]
