# Generated by Django 5.0 on 2024-03-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_category_name_alter_task_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.AddField(
            model_name='task',
            name='categories',
            field=models.ManyToManyField(related_name='category', to='tasks.category'),
        ),
    ]
