# Generated by Django 5.0 on 2024-03-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_task_category_task_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='categories',
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(default='Study', max_length=255),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
